# Generated by Django 4.0.4 on 2022-04-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipeingredient_unique_together'),
        ('core', '0003_alter_pantryusertest_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PantryUserTest',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='pantry',
            old_name='pantryusertest',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='pantryingredient',
            unique_together={('pantry', 'ingredient')},
        ),
    ]
