# Generated by Django 4.0.4 on 2022-04-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredientcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'verbose_name_plural': 'Ingredient categories'},
        ),
    ]
