# Generated by Django 4.0.4 on 2022-05-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default='recipe_def.jpg', upload_to='recipe_images'),
        ),
    ]
